### ISSUE TITLE
Dark theme is not working with all pages and components

### ISSUE THREAD

**Issue by DanielDimitrov5** [DanielDimitrov5/NFT-Marketplace-FE#12]
<b>Dart theme</b> feature is awesome, but it's not working good on some pages and components. For example the navigation dropdown is broken and the titles are not visible. The collection page is also not looking good. And lastly the 'add item' and 'my items' pages also need a fix.
<img width="1511" alt="SCR-20240125-rfpk" src="https://github.com/DanielDimitrov5/NFT-Marketplace-FE/assets/77460379/d552f44e-1069-43ec-8cd1-a31ec6bcecf7">
<img width="1512" alt="SCR-20240125-rfie" src="https://github.com/DanielDimitrov5/NFT-Marketplace-FE/assets/77460379/9c23a234-9786-4b65-990b-df8d097b72d5">

@MertJSX

**Comment by MertJSX** [comment]
Yes, I've fixed the dropdown bug in my last pull request. But I'm still working on bugs on other pages, like My Items.

**Comment by DanielDimitrov5** [comment]
Fixed!
